---
openapi: 3.0.3
info:
  title: museum-railway-backend API
  version: 1.0-SNAPSHOT
paths:
  /api/location:
    get:
      tags:
      - Locations Resource
      parameters:
      - name: operatorId
        in: query
        schema:
          type: string
          nullable: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MuseumLocation'
  /api/manage/reloadData:
    post:
      tags:
      - Management Resource
      responses:
        "201":
          description: Created
  /api/operator:
    get:
      tags:
      - Operators Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MuseumOperator'
components:
  schemas:
    Location:
      required:
      - country
      - state
      - street
      type: object
      properties:
        lat:
          format: float
          type: number
        lon:
          format: float
          type: number
        country:
          type: string
        state:
          type: string
        street:
          type: string
        city:
          type: string
          nullable: true
        zipCode:
          type: string
          nullable: true
    MuseumLocation:
      required:
      - name
      - type
      - operatorId
      - eventLocationId
      - webUrl
      - description
      - imageName
      - eventCollectorType
      - eventCollectionNotPossibleReason
      - location
      type: object
      properties:
        name:
          type: string
        type:
          $ref: '#/components/schemas/MuseumType'
        operatorId:
          type: string
        eventLocationId:
          type: string
        webUrl:
          type: string
        description:
          type: string
        imageName:
          type: string
        eventCollectorType:
          type: string
        eventCollectionNotPossibleReason:
          type: string
        location:
          $ref: '#/components/schemas/Location'
    MuseumOperator:
      required:
      - name
      - identifier
      - webUrl
      - description
      - imageName
      - location
      type: object
      properties:
        name:
          type: string
        identifier:
          type: string
        webUrl:
          type: string
        description:
          type: string
        imageName:
          type: string
        location:
          $ref: '#/components/schemas/Location'
    MuseumType:
      enum:
      - Museum
      - ModelRailway
      - Station
      - Event
      - RailLine
      type: string
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
